---
title: "Plans"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: journal
---

# Overview 

This is a workspace for discussion. 

## Meetings 

Tuesday: 15.00 
Thursday: 17.00

## Workshops

Monday
Friday

# Summary 

Rule 1. Communicate 
Rule 2. Adjust 
Rule 3. In advance 

## Trials (from the book)

There are two possible outcomes for each trial. Each field goal is a success or failure. Notice that we could further divide failures into other categories: too short, long enough but to the left of the uprights, long enough but to the right of the uprights, or some combinations of these. If our interest is only in whether the kick is successful, then differentiating among the modes of failure is not necessary (cited).

## North 

rom North's School, is looking for new of telling stories that can better engage diverse audiences. Read our inaugural post (cited)

## South 

Each field goal is a success or failure. Notice that we could further divide failures into other categories: too short, long enough but to the right of the uprights, long enough but to the right of the uprights, or some combinations of these. If our interest is only in whether the kick is successful, then differentiating among the modes of failure is not necessary (cited). 

## East 

Each field goal is a success or failure. Notice that we could further divide failures into other categories: too short, long enough but to the left of the uprights, long enough but to the right of the uprights, or some combinations of these. If our interest is only in whether the kick is successful, then differentiating among the modes of failure is not necessary (cited).

## West 

Each field goal is a success or failure. Notice that we could further divide failures into other categories: too short, long enough but to the left of the uprights, long enough but to the right of the uprights, or some combinations of these. If our interest is only in whether the kick is successful, then differentiating among the modes of failure is not necessary (cited).

